[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

# SPA routing: serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
